Create Table [User]
(
Id VARCHAR(36) PRIMARY KEY NOT NULL DEFAULT CONVERT(VARCHAR(36), NEWID(), 0),
IdentificationTypeId VARCHAR(36) REFERENCES IdentificationType(Id) ON UPDATE CASCADE NOT NULL,
IdentificationNumber VARCHAR(15) UNIQUE NOT NULL,
CompanyName VARCHAR(100),
FirstName VARCHAR(50),
SecondName VARCHAR(50),
FirstLastName VARCHAR(50),
SecondLastName VARCHAR(50),
Email VARCHAR(50)
)