CREATE TABLE Contact
(
Id VARCHAR(36) PRIMARY KEY NOT NULL DEFAULT CONVERT(VARCHAR(36), NEWID(), 0),
ViaId VARCHAR(36) REFERENCES Via(Id) ON UPDATE CASCADE NOT NULL,
Nro1 VARCHAR(3),
Letra1 VARCHAR(3),
Nro2 VARCHAR(3),
Letra2 VARCHAR(3),
NroyComplementos VARCHAR(50),
MunicipioId VARCHAR(36) REFERENCES Municipio(Id) ON UPDATE CASCADE NOT NULL,
Telefono1 VARCHAR(15)
)